### ISSUE TITLE
Not displaying Large fonts

### ISSUE THREAD

**Issue by elgranshaman** [bitbank2/ss_oled#10]
Hello,

I am running the example code:

```
#include <ss_oled.h>

void setup() {
  int rc = oledInit(OLED_128x32, 0, 0, -1, -1,400000L); // use standard I2C bus at 400Khz
}

void loop() {
  oledFill(0x0, 1);
  oledWriteString(0,0,0,"DEMO", FONT_STRETCHED, 0, 1);
  while(1)
  {
    
  }
}
```

And is working fine, except that when input FONT_LARGE, nothing appears on the display. For all other font types, I can see "DEMO" on the screen.

I am using an ATTiny1684 and the 128x32 OLED display.

**Comment by bitbank2** [comment]
As I documented in the README, the large font takes an additional 6K of FLASH space, so it is disabled on AVR targets (such as your ATTiny). That's why I added the FONT_STRETCHED option.
