### ISSUE TITLE
Scrolling text on ATTiny

### ISSUE THREAD

**Issue by elgranshaman** [bitbank2/ss_oled#11]
Is it possible to use the scrolling function on the ATTiny? If so, could you please give me an example of how to horizontally scrolltext?

Thanks a lot

**Comment by bitbank2** [comment]
Good question. Yes, you can use the scrolling text feature on any target. The first parameter to the oledWriteString() function is the scroll offset. This represents the number of pixels that the text is scrolled to the left. For example, to display the text from the start, set it to 0. To scroll the text 10 pixels to the left, set it to 10. This allows you to define a long string which doesn't fit on the display and show it scrolling left or right 1 pixel at a time.
