### ISSUE TITLE
[Feature request] Support RST line

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/ss_oled#14]
Can we have RST line support for SSD1306 in the library?

**Comment by bitbank2** [comment]
It is already supported. See https://github.com/bitbank2/ss_oled/blob/master/src/ss_oled.cpp line 691.
If this is not sufficient, can you explain better what you're looking for?

**Comment by cyberman54** [comment]
...but only for SPI interface, not for I2C:
`int oledInit(int iType, int bFlip, int bInvert, int sda, int scl, int32_t iSpeed)`

**Comment by bitbank2** [comment]
The common SSD1306 modules available to the public don't expose the reset line when they come configured for I2C. It's not exposed because it's not needed. Can you show me a situation where the reset line is needed on a SSD1306 configured for I2C?

**Comment by cyberman54** [comment]
On Heltec ESP32 Wifi Lora32 boards, v1 and v2, the SSD1306 is I2C driven AND the RST line is connected. This is useful to clear the display.

**Comment by cyberman54** [comment]
Look here:
https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/tree/master/SchematicDiagram/WiFi_LoRa_32(V2)

**Comment by bitbank2** [comment]
One vendor selling one board which has the reset line exposed is not a compelling argument. If you want to add that functionality, then I suggestion you fork my library and add it. Otherwise it doesn't add any value to the vast majority of people using it.
