### ISSUE TITLE
y-axis point resolution scrolling and character positioning

### ISSUE THREAD

**Issue by jgrulich** [bitbank2/ss_oled#21]
I've found this lib very useful and now hit one limitation with y-axis. It's done for line of 8 points.
But for smooth vertical scrolling is needed to use point resolution, same as is used for horizontal one.
The same story it is, when I need to place some character at exact x,y position.
I've tried to look around the code, but not able to locate the right direction.
Please be so kind and help.

**Comment by bitbank2** [comment]
Thanks for letting me know you find it useful. The limitation on Y coordinate placement has to do with the memory layout of the OLED. For simplicity, the font functions draw only on byte boundaries. If you would like finer vertical scrolling, take a look at the oledScrollBuffer() function.
