### ISSUE TITLE
Can't make in linux

### ISSUE THREAD

**Issue by linuxgnuru** [bitbank2/ss_oled#24]
pinMode, digitalWrite, delay, OUTPUT, HIGH, and LOW are undefined and it will not make.  I had to manually add #include <wiringPi.h> to src/ss_oled.cpp under #ifdef _LINUX_ in order to add these.

**Comment by bitbank2** [comment]
I just got hold of a RPI4 and updated the code to run on Linux. Take note that the functions have changed to include a SSOLED structure pointer. This allows ss_oled to control any number of displays simultaneously.
