### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by jtannenba** [bitbank2/ss_oled#27]
Trying this with pluggable ATtiny85 Digispark and 1.3" SSH1106 Oled.  Get this error when compiling in Arduino ver 1.8.12: Example: oled animation demo:

Arduino: 1.8.12 (Windows 10), Board: "Digispark (Default - 16.5mhz)"

Warning: Board breadboard:avr:atmega328bb doesn't define a 'build.board' preference. Auto-set to: AVR_ATMEGA328BB
C:\Users\Tannenba\Documents\Arduino\libraries\BitBang_I2C\src\BitBang_I2C.cpp: In function 'int i2cByteOutAVR(uint8_t)':

C:\Users\Tannenba\Documents\Arduino\libraries\BitBang_I2C\src\BitBang_I2C.cpp:294:19: error: 'iDelay' was not declared in this scope

          sleep_us(iDelay);

                   ^
I changed use HW I2C to 1
sda to 0
and scl 2.

**Comment by bitbank2** [comment]
This issue is with the BitBang_I2C library, not ss_oled. I fixed it and created a new release of that library (2.0.1).
