### ISSUE TITLE
Wrong return code when false address given

### ISSUE THREAD

**Issue by alrabe** [bitbank2/ss_oled#33]
Hi

Just started with the library. I found out: If providing a wrong I2C address, then a wrong return code will be returned. **oledInit()** will return a **5** (OLED_SH1107_3D), but I would expect to get **OLED_NOT_FOUND**.

Alex

**Comment by bitbank2** [comment]
I just pushed a fix to the master branch. Please confirm and I'll do a new release.

**Comment by alrabe** [comment]
I confirm. Setting wrong address will return now -1. Setting the correct address or -1 works still fine.
