### ISSUE TITLE
STM32 Blue Pill Compatibility

### ISSUE THREAD

**Issue by roboticboyer** [bitbank2/ss_oled#35]
The ss_oled library is compatible with STM32duino boards such as the Blue Pill F103C8T6
These pin numbers are for the Blue Pill
```
#define SDA_PIN PB7
#define SCL_PIN PB6
```
I suggest to reference this compatibility in the library description

**Comment by bitbank2** [comment]
Thanks for the heads up; I think I state pretty clearly that this code should run on ALL Arduino compatible boards. There's really nothing preventing it from running on anything. The specifics about which pins should be used for hardware vs software I2C on each board are not something I want to document.
