### ISSUE TITLE
Sign "Umlautu" - german ü

### ISSUE THREAD

**Issue by ghost** [bitbank2/ss_oled#36]
Hi developer!

could i have the code for print an "ü" sign ?

ive nothing found :-(

thanks a lot
Patrick

**Comment by bitbank2** [comment]
Hi Patrick,
I'm sorry, but the accented characters are not in there. One of the goals of ss_oled is to small, so only 96 ASCII characters are present in the fonts. If you switch to my OneBitDisplay library and provide a proportional font (Adafruit GFX format), you can have a full character set.
