### ISSUE TITLE
Print degree symbol ° ?

### ISSUE THREAD

**Issue by heresiarch** [bitbank2/ss_oled#38]
Hello,how I could add degree ° Symbol to the font table?
Drawing an Ellipse is a workaround since I need to mix x y cols and rows for characters with graphic x,y coordinates.

**Comment by cyberman54** [comment]
use onebitdisplay library instead, and load a custom font.

**Comment by bitbank2** [comment]
You can use a different font. The built-in fonts are very limited in order save space. With my OneBitDisplay library, you can use an Adafruit formatted font that you supply.

**Comment by Afzalkhan-devv** [comment]
Please anyone know how this webpage uses copy command in above of their posts (degreessymbolsign.com). See the webpage that is designed well and how to Print degree symbol ° understands by this webpage well. please help i want to make a website on [Degree symbol mac](https://degreessymbolsign.com/)

**Comment by Afzalkhan-devv** [comment]
force quit on mac is easy but how to manage [service host sysmain ](https://windowliveupdates.com/service-host-sysmain/)in windows.
