### ISSUE TITLE
Teensy LC + SH1106 - Everything is offset by a couple of pixels to the left

### ISSUE THREAD

**Issue by SpMakris** [bitbank2/ss_oled#41]
I am running the simple demo on a Teensy LC using a waveshare 1'' OLED (SH1106). Everything is printed as if it was offset by a couple of pixels to the left. The rightmost side of the display shows trash (random pixels). It looks like some index goes out of bounds. What am I doing wrong?

**Comment by bitbank2** [comment]
Try initializing it explicitly with type OLED_132x64 (SH1106).

**Comment by SpMakris** [comment]
That solved the problem, thanks!
