### ISSUE TITLE
SPI support

### ISSUE THREAD

**Issue by Bjoernolav** [bitbank2/ss_oled#44]
Is SPI currently supported by the library? When attempting to call the `oledSPIInit` function, the Arduino IDE complains that it does not manage to find the implementation of the function. https://github.com/bitbank2/ss_oled/blob/a0970f775c148abd0ad722e793db51b1135c2273/src/ss_oled.h#L79

When digging a bit, it seems that the implementation requires that the `FUTURE` flag is set: https://github.com/bitbank2/ss_oled/blob/a0970f775c148abd0ad722e793db51b1135c2273/src/ss_oled.cpp#L681-L683

When attempting to add `#define FUTURE`, several other problems appear.

Am I doing something wrong, or is not SPI supported yet as stated in the README?

**Comment by bitbank2** [comment]
ss_oled was strictly I2C. For SPI I decided to create a more comprehensive library which deprecates ss_oled. The new library is called OneBitDisplay and includes all of the features of ss_oled along with new ones. Please use this one from now on.
