### ISSUE TITLE
There is no example of oledDrawSprite

### ISSUE THREAD

**Issue by Tilation** [bitbank2/ss_oled#49]
void oledDrawSprite(SSOLED *pOLED, uint8_t *pSprite, int cx, int cy, int iPitch, int x, int y, uint8_t iPriority)
argument pOLED is the oled
argument pSprite is the sprite
what are the rest? this function's documentation doesn't describe all the arguments.
How do you use this?
cx is meant to be center x? is iPitch the rotation?

**Comment by bitbank2** [comment]
cx = width in pixels
cy = height in pixels
iPitch = bytes per source line (e.g. 34 pixels wide would be 5 bytes, but it can be any value you tell it)
x,y = destination coordinates
Priority tells which bit 0/1 is the transparent part and which is the opaque part
Please write an example if you like.
This library is deprecated and OneBitDisplay is the currently supported one.
