### ISSUE TITLE
Support for 64x48 display

### ISSUE THREAD

**Issue by fijam** [bitbank2/ss_oled#51]
Would it be possible to add support for a 1306-based 64x48px display?

Product pictured below, tested with adafruit_ssd1306 python library.

![IMG_20210902_120357](https://user-images.githubusercontent.com/75824/131825683-9c669d3f-a90b-4207-8d51-add7fa41b54e.jpg)

**Comment by bitbank2** [comment]
I don't have that size handy to test. It isn't hard to add support, but you need to verify the init sequence (2 possible ones) and the memory offset of the visible portion of the display. At the moment I can't do that verification without having a display in hand.

**Comment by fijam** [comment]
Can you describe in more detail how to calculate the memory offset? I could give it a shot.

**Comment by bitbank2** [comment]
If you look at the code, you'll see the various x/y offset values that are set up in init() depending on the display chosen. It's not a matter of calculating it, but a matter of figuring out the value by trial and error. The info is not documented and can't be guessed.
