### ISSUE TITLE
FONT_16x32 and FONT_LARGE not displaying on 128x32 OLED

### ISSUE THREAD

**Issue by rschaer** [bitbank2/ss_oled#59]
Any string that is set to be shown at FONT_16x32 or FONT_LARGE, doesn't seem to get rendered to the 128x32 screen. Noticed this in the simple_demo as well as my own code. Tested with two different screens, setting different rows, same result. Is this to be expected for the 128x32 screen?

This will show "TEXT" on screen:
```
oledFill(&ssoled, 0x0, 1);
oledWriteString(&ssoled, 0,0,0,(char *)"TEXT", FONT_LARGE, 0, 1);
delay(2000);
```

This will create a blank screen for me:
```
oledFill(&ssoled, 0x0, 1);
oledWriteString(&ssoled, 0,0,0,(char *)"TEXT", FONT_LARGE, 0, 1);
delay(2000);
```

**Comment by bitbank2** [comment]
These are disabled in the code on AVR targets to save FLASH space. You can undo the "#ifdefs" if you want them to be available.
