### ISSUE TITLE
No pixel drawing on AVR - Arduino nano or ATTINY1604

### ISSUE THREAD

**Issue by alunmorris** [bitbank2/ss_oled#63]
Platform: Windows 10. Arduino 2.3.2

I tried the "Small Simple OLED library demo for AVR platform" example.

The text prints fine in loop() but no pixels are drawn. Also oledInit() returns -1.

Tried with a nano board and an ATTINY1604. Tried with Arduino 1.8.3.

**Comment by bitbank2** [comment]
The default for AVR is to disable the back buffer since it has so little RAM. The set pixel function will not work without a back buffer since the minimum write size is 1 byte (8 pixels).
P.S. This library is deprecated; OneBitDisplay is my currently supported library.

**Comment by alunmorris** [comment]
Thanks. Will look at OneBitDisplay.
