### ISSUE TITLE
Strange text on ESP32 CAM 128x128

### ISSUE THREAD

**Issue by step135** [bitbank2/ss_oled#64]
I don't see desired text only some special chars and many times only black screen.  https://aliexpress.com/item/1005006782017574.html

**Comment by step135** [comment]
PINS are 13 and 14.

**Comment by step135** [comment]
GPIOs for I2C are 14 and 15.

**Comment by step135** [comment]
It works, but your example `simple-demo.ino` doesn't work.

**Comment by bitbank2** [comment]
This repo is deprecated and I'm sorry I can't provide any support for the issue you found.
