### ISSUE TITLE
oledDrawLine(&ssoled, 10, 40, 118, 40, 1); causing reboot

### ISSUE THREAD

**Issue by step135** [bitbank2/ss_oled#66]
```
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
```

**Comment by bitbank2** [comment]
This repo is deprecated and I'm sorry I can't provide any support for the issue you found.

**Comment by step135** [comment]
Why is it still active in Arduino IDE under libraries to install?

**Comment by bitbank2** [comment]
It's still functional and useful, but imperfect (as all open source code is). Would you rather that I delete it from existence?
