### ISSUE TITLE
Other device working, but not detected.

### ISSUE THREAD

**Issue by rin67630** [bitbank2/ss_oled#67]
Hi,

I am pleased to report that your lib works with the device described here
https://github.com/peff74/esp8266_OLED_HW-364A/ (a lib, that does not work any more with an ESP8266)
using
`
#define SDA_PIN 14
#define SCL_PIN 12
`

The only caveat is that 
`rc = oledInit(&oled, OLED_128x64, 0x3c, FLIPPED, INVERTED, HARDWARE_I2C, SDA_PIN, SCL_PIN, RESET_PIN, 1000000L);
`
returns -1 

Can that be fixed easily?

**Comment by bitbank2** [comment]
I'm sorry, but I'm no longer supporting this llibrary. The code is not very complicated. Take a look at the init function and you can probably figure out where the failure is occurring.
