### ISSUE TITLE
Oled 128x128 and dumpbuffer bug

### ISSUE THREAD

**Issue by GitHubLionel** [bitbank2/ss_oled#68]
Hi

I have a problem with dumpbuffer and oled128x128 (SH1107).
The screen is not correctly rendered. The upper half of the screen is correct but the bottom half is copied over the upper half.
You can reproduce the problem with the simple_demo.ino code with this lines in the loop: 
```
	  oledFill(&ssoled, 0x0, 0);
	  oledWriteString(&ssoled, 0,0,0,"upper", FONT_SMALL, 0, 0);
	  oledWriteString(&ssoled, 0,0,10,"bottom", FONT_SMALL, 0, 0);
	  oledDumpBuffer(&ssoled, NULL);
          delay(2000);
```
The problem is the same with backbuffer.

**Comment by bitbank2** [comment]
I'm sorry, but this library is deprecated. You're not showing me your whole sketch. Are you selecting the correct type of display? Try my newer library https://github.com/bitbank2/OneBitDisplay.

**Comment by GitHubLionel** [comment]
Hi,
Thank's for your answer.
I try OneBitDisplay library but I have others problems with it.

But after 2 days of research, I finally found the bug. There is in `oledWriteDataBlock ` function in line 1025. For my oled 128x128, this not 1027 but 2047 !
