### ISSUE TITLE
Sudden errors

### ISSUE THREAD

**Issue by GreyArea1966** [bitbank2/ss_oled#8]
Dunno if this is related to antman2's issue from a couple weeks ago, but getting huge error list - telling me things like "oledFill" now needs two parameters instead of one.

How do I get around this?

**Comment by bitbank2** [comment]
I added some features to 2.0.0 and one of them was delayed rendering. It means you must add an additional parameter (render to display or just to memory). This applies to all of the functions. I also added a horizontal scroll offset to the text drawing function. Please see the .H file for the function prototypes and the new demo code.
